name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      - name: Get CPM
        uses: engineerd/configurator@v0.0.10
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe
      
      - name: Build libraries
        run: cpm -v --proto https -u https://github.com/neacsum/utf8.git -r $HOME utf8
        
      - name: Run tests
        shell: cmd
        run: |
          echo %USERPROFILE% 
          dir %USERPROFILE%
          echo %USERPROFILE%\utf8
          dir %USERPROFILE%\utf8
          echo %USERPROFILE%\utf8\build
          dir %USERPROFILE%\utf8\build
          echo %USERPROFILE%\utf8\build\x64\tests
          dir %USERPROFILE%\utf8\build\x64\tests
          dir %USERPROFILE%\utf8\build\x64\tests\Release
          echo %USERPROFILE%\utf8\build\x64\tests\Release
          %USERPROFILE%\utf8\build\x64\tests\Release\tests.exe
